version: '3'
services:
    app:
        build: .
        depends_on:
            - db_host
        ports:
            - "5001:5001"

    db_host:
        image: mongo:latest
        ports:
            - "27017:27017"
